# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: 2

issues:
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - govet

formatters:
  enable:
    - gofmt
    - goimports
